version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:30"
    target-branch: "dev"
    assignees:
      - "hibare"

  # Maintain dependencies for Go mods
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:30"
    target-branch: "dev"
    assignees:
      - "hibare"
    allow:
      # Allow only direct updates for
      - dependency-type: "direct"

  # Maintain version for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:30"
    target-branch: "dev"
    assignees:
      - "hibare"
