version: "3"

services:
  go-container-status:
    image: cosmtrek/air
    container_name: go-container-status
    hostname: go-container-status
    working_dir: /app
    user: ${HOST_UID}:${HOST_GID}
    command: -c air.toml
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/app
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
